server_name: "test"

report_stats: false

database:
  name: "psycopg2"
  args:
    user: postgres
    host: postgres
    password: postgres
    database: synapse

trusted_key_servers:
  - server_name: "matrix.org"

suppress_key_server_warning: true
